name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests for ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: python -m pip install .
      - name: Run
        run: python test.py
      - run: cp test.py test_.py
      - name: Bisect
        run: git bisect start && git bisect bad && git bisect good v2.0.3 && git bisect run bash -x -c 'PYTHONPATH=src python test_.py | grep FileModifiedEvent'
